ANT = "Ant"
BEAVER = "Beaver"
CRICKET = "Cricket"
DUCK = "Duck"
FISH = "Fish"
HORSE = "Horse"
MOSQUITO = "Mosquito"
OTTER = "Otter"
PIG = "Pig"
SLOTH = "Sloth"
CRAB = "Crab"
DODO = "Dodo"
DOG = "Dog"
ELEPHANT = "Elephant"
FLAMINGO = "Flamingo"
HEDGEHOG = "Hedgehog"
PEACOCK = "Peacock"
RAT = "Rat"
SHRIMP = "Shrimp"
SPIDER = "Spider"
SWAN = "Swan"
BADGER = "Badger"
BLOWFISH = "Blowfish"
CAMEL = "Camel"
GIRAFFE = "Giraffe"
KANGAROO = "Kangaroo"
OX = "Ox"
RABBIT = "Rabbit"
SHEEP = "Sheep"
SNAIL = "Snail"
TURTLE = "Turtle"
WHALE = "Whale"
BISON = "Bison"
DEER = "Deer"
DOLPHIN = "Dolphin"
HIPPO = "Hippo"
MONKEY = "Monkey"
PENGUIN = "Penguin"
ROOSTER = "Rooster"
SKUNK = "Skunk"
SQUIRREL = "Squirrel"
WORM = "Worm"
COW = "Cow"
CROCODILE = "Crocodile"
PARROT = "Parrot"
RHINO = "Rhino"
SCORPION = "Scorpion"
SEAL = "Seal"
SHARK = "Shark"
TURKEY = "Turkey"
CAT = "Cat"
DRAGON = "Dragon"
FLY = "Fly"
GORILLA = "Gorilla"
LEOPARD = "Leopard"
MAMMOTH = "Mammoth"
SNAKE = "Snake"
TIGER = "Tiger"

# summoned only pets
ZOMBIE_CRICKET = "Zombie Cricket"
BUS = "Bus"
ZOMBIE_FLY = "Zombie Fly"
DIRTY_RAT = "Dirty Rat"
CHICK = "Chick"
RAM = "Ram"
BUTTERFLY = "Butterfly"
BEE = "Bee"

# expansion pets
BEETLE = "Beetle"
BLUEBIRD = "Bluebird"
LADYBUG = "Ladybug"
BAT = "Bat"
DROMEDARY = "Dromedary"
TABBY_CAT = "Tabby Cat"
CATERPILLAR = "Caterpillar"
HATCHING_CHICK = "Hatching Chick"
OWL = "Owl"
PUPPY = "Puppy"
TROPICAL_FISH = "Tropical Fish"
BUFFALO = "Buffalo"
LLAMA = "Llama"
LOBSTER = "Lobster"
POODLE = "Poodle"
CHICKEN = "Chicken"
EAGLE = "Eagle"
GOAT = "Goat"
MICROBE = "Microbe"
OCTOPUS = "Octopus"
SAUROPOD = "Sauropod"
TYRANNOSAURUS = "Tyrannosaurus"
BUTTERFLY = "Butterfly"

# foods
APPLE = "Apple"
HONEY = "Honey"
CUPCAKE = "Cupcake"
MEAT_BONE = "Meat Bone"
SLEEPING_PILL = "Sleeping Pill"
GARLIC = "Garlic"
SALAD_BOWL = "Salad Bowl"
CANNED_FOOD = "Canned Food"
PEAR = "Pear"
CHILI = "Chili"
CHOCOLATE = "Chocolate"
SUSHI = "Sushi"
MELON = "Melon"
MUSHROOM = "Mushroom"
PIZZA = "Pizza"
STEAK = "Steak"
MILK = "Milk"

# statuses
WEAK = "Weak"
COCONUT_SHIELD = "Coconut Shield"
HONEY_BEE = "Honey Bee"
BONE_ATTACK = "Bone Attack"
GARLIC_ARMOR = "Garlic Armor"
SPLASH_ATTACK = "Splash Attack"
MELON_ARMOR = "Melon Armor"
EXTRA_LIFE = "Extra Life"
STEAK_ATTACK = "Steak Attack"
POISON_ATTACK = "Poison Attack"

# ability triggers
FAINT = "Faint"
SELL = "Sell"
EATS_SHOP_FOOD = "EatsShopFood"
END_OF_TURN = "EndOfTurn"
LEVEL_UP = "LevelUp"
SUMMONED = "Summoned"
BUY_FOOD = "BuyFood"
START_OF_BATTLE = "StartOfBattle"
BUY = "Buy"
START_OF_TURN = "StartOfTurn"
BEFORE_ATTACK = "BeforeAttack"
HURT = "Hurt"
AFTER_ATTACK = "AfterAttack"
END_OF_TURN_WITH_2_PLUS_GOLD = "EndOfTurnWith2PlusGold"
BUY_AFTER_LOSS = "BuyAfterLoss"
END_OF_TURN_WITH_LVL_3_FRIEND = "EndOfTurnWithLvl3Friend"
KNOCK_OUT = "KnockOut"
END_OF_TURN_WITH_4_OR_LESS_ANIMALS = "EndOfTurnWith4OrLessAnimals"
BUY_TIER_1_ANIMAL = "BuyTier1Animal"
CASTS_ABILITY = "CastsAbility"
END_OF_TURN_WITH_3_PLUS_GOLD = "EndOfTurnWith3PlusGold"
WHEN_DAMAGED = "WhenDamaged"
WHEN_ATTACKING = "WhenAttacking"

# ability triggerBys
SELF = "Self"
PLAYER = "Player"
EACH_FRIEND = "EachFriend"
FRIEND_AHEAD = "FriendAhead"

# ability effect kinds
MODIFY_STATS = "ModifyStats"
SUMMON_PET = "SummonPet"
DEAL_DAMAGE = "DealDamage"
GAIN_GOLD = "GainGold"
APPLY_STATUS = "ApplyStatus"
TRANSFER_STATS = "TransferStats"
ONE_OF = "OneOf"
SUMMON_RANDOM_PET = "SummonRandomPet"
GAIN_EXPERIENCE = "GainExperience"
EVOLVE = "Evolve"
ALL_OF = "AllOf"
SWALLOW = "Swallow"
REDUCE_HEALTH = "ReduceHealth"
REFILL_SHOPS = "RefillShops"
TRANSFER_ABILITY = "TransferAbility"
FOOD_MULTIPLIER = "FoodMultiplier"
REPEAT_ABILITY = "RepeatAbility"
FAINT = "Faint"
MODIFY_DAMAGE = "ModifyDamage"
SPLASH_DAMAGE = "SplashDamage"
RESPAWN_PET = "RespawnPet"

# ability effect target kinds
RANDOM_FRIEND = "RandomFriend"
EACH_SHOP_ANIMAL = "EachShopAnimal"
LEFT_MOST_FRIEND = "LeftMostFriend"
EACH_FRIEND = "EachFriend"
TRIGGERING_ENTITY = "TriggeringEntity"
SELF = "Self"
RANDOM_ENEMY = "RandomEnemy"
FRIEND_BEHIND = "FriendBehind"
ALL = "All"
ADJACENT_ANIMALS = "AdjacentAnimals"
FRIEND_AHEAD = "FriendAhead"
ADJACENT_FRIENDS = "AdjacentFriends"
LOWEST_HEALTH_ENEMY = "LowestHealthEnemy"
RIGHT_MOST_FRIEND = "RightMostFriend"
LEVEL_2_AND_3_FRIENDS = "Level2And3Friends"
DIFFERENT_TIER_ANIMALS = "DifferentTierAnimals"
HIGHEST_HEALTH_ENEMY = "HighestHealthEnemy"
LAST_ENEMY = "LastEnemy"
FIRST_ENEMY = "FirstEnemy"
EACH_ENEMY = "EachEnemy"
PURCHASE_TARGET = "PurchaseTarget"

# probability kinds
SHOP = "shop"
LEVELUP = "levelup"

# turns
TURN_1 = "turn-1"
TURN_2 = "turn-2"
TURN_3 = "turn-3"
TURN_4 = "turn-4"
TURN_5 = "turn-5"
TURN_6 = "turn-6"
TURN_7 = "turn-7"
TURN_8 = "turn-8"
TURN_9 = "turn-9"
TURN_10 = "turn-10"
TURN_11 = "turn-11"

# pack names
PACK_NAME_STANDARD = "StandardPack"
PACK_NAME_EXPANSION = "ExpansionPack1"

# error constants
ERROR_STILL_ALIVE = "Can't use ability: Pet still alive"
ERROR_NOT_ALIVE = "Can't use ability: Pet not alive"
ERROR_ALL_FRIENDS_DEAD = "Can't use ability: All Friends dead"
